tests/test_client.py, workos/__about__.py, workos/audit_log.py, workos/sso.py, workos/utils/request.py, workos/utils/validation.py
[Asana](https://app.asana.com/0/0/1161174977831258/f)
This PR adds support for promoting Draft Connections that have been created via the IdP Link embed.
=> Support Promoting Draft Connections

workos/sso.py
This updates the SDK to work with changes to the `activate` endpoint.
=> update activate endpoint

workos/sso.py
This PR updates references to IdP Link to WorkOS.js
=> Update comments referencing IdP Link to WorkOS.js

tests/test_directory_sync.py, workos/directory_sync.py
Adds function to fetch list of Directories from the WorkOS API.
=> Add fetching list of Directory Endpoints

setup.py, workos/__init__.py, workos/audit_trail.py, workos/utils/request.py, workos/utils/validation.py
[Asana](https://app.asana.com/0/1171846862894397/1172310005552425/f)
Grab bag of things:
- Fix validation exception message
- Fix use of idempotency key
- Post JSON so that metadata from audit trail events get into WorkOS properly
- Add enum dependency for version of python that don't have it (<3.4)
- Grab api key and project id from env by default
=> Random FIxes

tests/test_client.py, tests/test_directory_sync.py, tests/test_portal.py, workos/client.py, workos/portal.py, workos/utils/validation.py
* Returns a list of the organizations accessible to the provided
API key. Includes pagination functionality via the list_metadata
property.
=> Add Portal module with list_organizations function

workos/__about__.py, workos/utils/connection_types.py
* Updates `connection_types` enum to reflect all Connection Types currently available in GA.
* Updates the SDK version to `0.8.1`.
=> Update Available Connection Types

README.md
Update link to the WorkOS API reference and add a link to the PyPi hosting page. Also make a few minor improvements to readability.
=> Update links and improve readability in README

README.md
https://linear.app/workos/issue/SDK-89/audit-readmes-in-sdks
=> README update for SDK consistency

tests/test_sso.py, workos/sso.py
PR to add the get_profile method and a corresponding unit test to the python SDK.
=> Add get_profile method and unit test

workos/utils/connection_types.py
Customer Slack thread: https://work-os.slack.com/archives/C0296SJCV6X/p1631546431000400
=> Add Microsoft OAuth to the connection type options

workos/__about__.py
Minor version bump to deploy SDK version 1.3.0.
=> Minor Version Bump to 1.3.0

workos/__about__.py
=> Patch version bump to 1.3.1

workos/__about__.py, workos/client.py
Fix missing underscore on client.py that prevents requests being routed to the webhooks class
=> Fix bug on client.py for webhooks

tests/test_directory_sync.py, workos/directory_sync.py
Add method to get single directory by id in the directory_sync class
=> Add method to get single directory

workos/__about__.py
Update version to 1.6.0 for release of get directory endpoint
=> Update version to 1.6.0

tests/test_sso.py, workos/sso.py
=> Add support for `domain_hint` and `login_hint` parameters

workos/directory_sync.py
Add Organization parameter to List Organizations
=> Add Organization parameter to List Directories

workos/__about__.py
Update version for 1.9.0 release (Add Organization parameter to List Directories)
=> Update version for release 1.9.0

tests/test_mfa.py, workos/mfa.py, workos/resources/mfa.py
Add MFA WorkOSChallenge class to make challenge response fields non-nullable
=> Add MFA WorkOSChallenge class to make challenge response fields non-nullable

workos/__about__.py
Update version with minor non-breaking-change - v1.12.0
=> Update version with minor non-breaking-change

workos/mfa.py
Forked from #129 to get CI to build the PR.
=> Fix `"is" with a literal` syntax warning

tests/test_organizations.py, workos/organizations.py
probably the docs page should be updated as well
=> Allow updating organization's `allow_profiles_outside_organization` flag

workos/__about__.py
=> Update SDK version 1.14.0

tests/test_sso.py, workos/sso.py, workos/utils/connection_types.py
Update validation for OAuth Provider ConnectionType
=> Update validation for OAuth Provider ConnectionType

tests/test_sso.py, workos/__about__.py, workos/sso.py, workos/utils/connection_types.py
=> Update version to 1.14.1

workos/utils/request.py
**BEFORE:**
`"User-Agent": "WorkOS Python/1.14.1"`
**AFTER:**
`"User-Agent": "WorkOS Python/3.10.6 Python SDK/1.14.1"`
=> Add Python version to the SDK user agent

workos/__about__.py
This should update the SDK to publish the following PRs:
https://github.com/workos/workos-python/pull/139
https://github.com/workos/workos-python/pull/140
=> Update version to 1.15.0

tests/test_directory_sync.py, workos/directory_sync.py, workos/resources/directory_sync.py
Add get_primary_email method to Directory Sync module
=> Add get_primary_email method to Directory Sync module

tests/test_organizations.py, workos/organizations.py
Add support for idempotency key in create_organization method
=> Add support for idempotency key in create_organization method

workos/__about__.py
=> Update version to 1.17.0

tests/test_directory_sync.py, workos/resources/directory_sync.py
Add job title to directory user
=> Add job title to directory user

workos/__about__.py
=> Update version to 1.20.0

workos/__about__.py
=> Update version to 1.20.1

tests/test_webhooks.py, workos/webhooks.py
Refactor webhooks validation method to decode event_body signature
=> Refactor webhooks validation method to decode event_body signature

workos/__about__.py
Update version to 1.20.2 for new release
=> Update version to 1.20.2 for new release

tests/test_portal.py, workos/portal.py
=> Add `log_streams` Admin Portal intent

workos/__about__.py
Update version to 1.23.0
```
[ ] Yes
```
=> Update version to 1.23.0

workos/__about__.py
Update version to 1.23.1
```
[ ] Yes
```
=> Update version to 1.23.1

setup.py
Update semaphore config to specify versions of requests and urllib3
```
[ ] Yes
```
=> Update semaphore config to specify versions of requests and urllib3

workos/__about__.py
Update version to 1.23.3
```
[ ] Yes
```
=> Update version to 1.23.3

workos/__about__.py
Update version to 1.24.0 
Added `events` [support](https://github.com/workos/workos-python/pull/180). 
```
[ ] Yes
```
=> Update version to 1.24.0

workos/__about__.py
- Updated `Events` API method to `list_events` 
```
[ ] Yes
```
=> Update version to v1.25.0

workos/__about__.py
* Use snake case for date range parameters in the Events API
```
[ ] Yes
```
=> Update version to v1.26.0

.github/workflows/ci.yml, ci/python-3_8/devbox.json, ci/python-3_8/devbox.lock, ci/python-3_9/devbox.json, ci/python-3_9/devbox.lock, devbox.json
This PR sets up GitHub Actions for CI, powered by Devbox.
```
[ ] Yes
```
=> Setup GitHub Actions

tests/test_users.py, workos/users.py
=> Add `Users.get_user()` method

tests/test_organizations.py, workos/organizations.py
=> Fix List Organizations V2

tests/test_users.py, workos/users.py
=> Add `Users.authenticate_with_code()`

tests/test_users.py, workos/resources/password_challenge_response.py, workos/users.py
=> Add `Users.create_password_challenge()` method

tests/test_users.py, workos/resources/magic_auth_challenge_response.py, workos/users.py
=> Add `Users.send_verification_email()` method

tests/test_users.py, workos/users.py
=> Add `users.delete_user()` method

tests/test_users.py, workos/users.py
=> Fix Verify Email Code method

tests/test_user_management.py, workos/user_management.py
Finalizes the email verification methods.
```
[ ] Yes
```
=> Finalize email verification methods

tests/test_user_management.py, tests/utils/fixtures/mock_user.py, workos/resources/user_management.py
=> Add profile_picture_url to the user object

.semaphore/publish.yml
=> Update image type

tests/test_user_management.py, workos/resources/user_management.py, workos/user_management.py
=> Support session tokens in auth response

workos/__about__.py
=> Bump version for session management apis

workos/__init__.py, workos/utils/request.py
Python SDK: Add 25 second default timeout to requests
```
[ ] Yes
```
=> Python SDK: Add 25 second default timeout to requests

workos/__about__.py
Bump version for request timeout feature addition
```
[ ] Yes
```
=> Bump version for request timeout feature addition

workos/__about__.py
Bump minor version for `role_slug` feature addition.
```
[ ] Yes
```
Related PR: https://github.com/workos/workos-python/pull/243
=> Bump minor version for role_slug feature addition

tests/test_user_management.py, workos/user_management.py
Adds missing JWKS and logout methods to the SDK.
```
[ ] Yes
```
=> Add JWKS and logout methods

workos/__about__.py
Bump to new release version.
```
[ ] Yes
```
=> Version bump to 4.7.0

tests/test_user_management.py, workos/user_management.py
Exposes the find invitation by token API endpoint
```
[x] Yes
```
https://github.com/workos/workos/pull/27785
=> Add find invitation by token method

tests/test_user_management.py, workos/__about__.py, workos/user_management.py
=> feat: add support for totp_secret

tests/test_user_management.py, workos/user_management.py
Add PKCE parameters to UM auth flow
```
[X] Yes
```
=> Add PKCE parameters to UM auth flow

workos/__about__.py
This version will include:
- https://github.com/workos/workos-python/pull/277
```
[ ] Yes
```
=> Bump version to 4.13.0

tests/test_client.py, tests/test_mfa.py, tests/utils/test_requests.py, workos/client.py, workos/mfa.py, workos/resources/mfa.py, workos/utils/request.py
Add typing for MFA.
```
[ ] Yes
```
=> Add typing for MFA

workos/resources/events.py, workos/resources/list.py, workos/resources/organizations.py, workos/resources/sso.py, workos/resources/user_management.py, workos/sso.py, workos/types/directory_sync/directory_user.py, workos/types/events/authentication_payload.py, workos/types/events/connection_payload_with_legacy_fields.py, workos/types/events/email_verification_payload.py, workos/types/events/organization_domain_verification_failed_payload.py, workos/types/events/session_created_payload.py, workos/types/organizations/organization_common.py, workos/types/organizations/organization_domain.py, workos/types/roles/role.py, workos/types/sso/connection.py, workos/types/user_management/email_verification_common.py, workos/types/user_management/impersonator.py, workos/types/user_management/invitation_common.py, workos/types/user_management/magic_auth_common.py, workos/types/user_management/password_reset_common.py
Type all of the other events.
One note, I have not yet added the [authentication events listed as coming soon](https://workos.com/docs/events/authentication)
As a follow-up PR I'll need to add a validator that returns an `UnrecognizedEvent` or similar if we receive an event type we don't recognize.
```
[ ] Yes
```
=> Type the rest of the events

workos/audit_logs.py, workos/events.py, workos/organizations.py, workos/portal.py, workos/resources/audit_logs.py, workos/resources/directory_sync.py, workos/resources/list.py, workos/resources/organizations.py, workos/resources/portal.py, workos/resources/sso.py, workos/types/directory_sync/directory_user.py, workos/types/events/directory_payload_with_legacy_fields.py, workos/types/organizations/organization_common.py, workos/types/roles/role.py
1. Move some input types near their usages to make them more discoverable
2. Switch all List -> Sequence
```
[ ] Yes
```
=> Type quality of life type updates

tests/conftest.py, tests/test_user_management.py, workos/async_client.py, workos/user_management.py, workos/utils/_base_http_client.py
Add async support for UM.
```
[ ] Yes
```
=> api: Add async support for UM

workos/organizations.py
The 5.0 version of [this change](https://github.com/workos/workos-python/commit/6ea991c1a674f8af9a9991b7f5b0424ff108283d) to the main SDK.
```
[ ] Yes
```
=> Name is optional when updating an organization

README.md, tests/conftest.py, workos/directory_sync.py, workos/events.py, workos/fga.py, workos/organizations.py, workos/sso.py, workos/types/list_resource.py, workos/types/user_management/authenticate_with_common.py, workos/types/user_management/authentication_response.py, workos/user_management.py
A few fixes from docs audit.
```
[ ] Yes
```
=> A few fixes from docs audit

tests/test_webhooks.py, workos/audit_logs.py, workos/directory_sync.py, workos/events.py, workos/fga.py, workos/mfa.py, workos/organizations.py, workos/passwordless.py, workos/portal.py, workos/sso.py, workos/types/fga/list_filters.py, workos/user_management.py, workos/webhooks.py
I did some slight cleanup as I noticed inconsistencies.
Tagged @atainter for FGA.
Resolves DSYNC-1758
```
[ ] Yes
```
=> Update Docstrings across the SDK

tests/conftest.py, tests/test_async_http_client.py, tests/test_audit_logs.py, tests/test_directory_sync.py, tests/test_events.py, tests/test_mfa.py, tests/test_organizations.py, tests/test_passwordless.py, tests/test_portal.py, tests/test_sso.py, tests/test_sync_http_client.py, tests/test_user_management.py, workos/user_management.py, workos/utils/_base_http_client.py
Fix bug for create_user and create_organization_membership and update all tests.
```
[ ] Yes
```
=> Fix bug for create_user and create_organization_membership and update all tests

workos/__about__.py
Bump to version 5.0.2.
```
[ ] Yes
```
=> Bump to version 5.0.2

workos/__about__.py
Changes include:
- https://github.com/workos/workos-python/pull/340
```
[ ] Yes
```
=> Bump version to 5.1.0

tests/test_portal.py, workos/types/portal/portal_link_intent.py
Add domain_verification intent
```
[ ] Yes
```
=> Add domain_verification intent

workos/__about__.py
Patch version bump.
```
[ ] Yes
```
=> Bump to 5.4.1

workos/__about__.py
Bump to version 5.4.3.
```
[ ] Yes
```
=> Bump to version 5.4.3

workos/__about__.py
Minor version bump to release #372 
```
[ ] Yes
```
=> Bump minor version - 5.5.0

setup.py
Update pydantic and mypy. Locally tested a handful of APIs across UM, DSync, and events, and verified pydantic breaking changes, none of which were relevant to our usage.
```
[ ] Yes
```
=> Update pydantic and mypy

workos/__about__.py
=> Bump to version 5.6.0

workos/__about__.py
Bump to version 5.7.0.
```
[ ] Yes
```
=> Bump to version 5.7.0

workos/__about__.py
=> Bump to version 5.9.0

workos/__about__.py
=> Bump to v5.10.0

workos/__about__.py
=> Release v5.12.0

workos/__about__.py
=> Bump to v5.14.0

workos/__about__.py
Which includes external id and metadata on users and organizations.
```
[ ] Yes
```
=> Bump to 5.16.0

workos/__about__.py
Bump to v5.17.0 to add `email` field to DirectoryUser.
```
[ ] Yes
```
=> Bump to v5.17.0

tests/conftest.py, tests/test_session.py, workos/session.py, workos/user_management.py
Add AsyncSession class and update tests.
```
[ ] Yes
```
=> Add AsyncSession class and update tests

workos/__about__.py
version bump that includes
- https://github.com/workos/workos-python/pull/429
```
[ ] Yes
```
=> bump version to 5.19.0

workos/__about__.py
=> Bump to 5.20.2
