tests/test_audit_log.py
tests/test_client.py
workos/__about__.py
workos/audit_trail.py
workos/client.py
workos/utils/validation.py

Renames the `audit_log` package to `audit_trail`.

rename audit log to audit trail

---

.gitignore
workos/__about__.py
workos/audit_trail.py
workos/utils/request.py

Expose data and params for the request helper as pass through kwargs. This'd allow to make the oauth post call with query params. Straightforward abstraction that I hope doesn't cause much confusion in the future.

Expose data and params kwargs for request helper

---

workos/__about__.py
workos/audit_trail.py
workos/utils/request.py

Getting a Profile as apart of the OAuth flow will now support having the bits passed over as form data.
Here's how my request to my local server looks with this change:
```
[api] [1584560790651] INFO  (32020 on henrys-mbp.lan): request completed
[api]     req: {
[api]       "id": 40,
[api]       "method": "POST",
[api]       "url": "/sso/token",
[api]       "headers": {
[api]         "host": "localhost:7000",
[api]         "user-agent": "WorkOS Python/0.2.2",
[api]         "accept-encoding": "gzip, deflate",
[api]         "accept": "*/*",
[api]         "connection": "keep-alive",
[api]         "content-length": "126",
[api]         "content-type": "application/x-www-form-urlencoded"
[api]       },
[api]       "body": {
[api]         "client_id": "dominos",
[api]         "client_secret": …
```

Move OAuth Post query params to form data

---

tests/test_audit_trail.py
tests/test_client.py
tests/test_directory_sync.py
workos/client.py
workos/directory_sync.py
workos/utils/validation.py

Add Python wrappers for the API reference endpoints [here](https://docs.workos.com/directory-sync/api-reference).

Add Directory Sync API and fix Audit Trail naming

---

tests/test_directory_sync.py
workos/directory_sync.py

Matching naming across our SDKs: https://github.com/workos-inc/workos-node/blob/master/src/directory-sync/directory-sync.ts.

Remove `directory` from Directory Sync module functions

---

tests/test_directory_sync.py
workos/directory_sync.py

* Re-factor `Directory Endpoint` to `Directory`
* Drop `_id` from Directory Sync kwargs
* Uses `/directory_users` instead of `/directories/:id/users`
* Uses `/directory_groups` instead of `/directories/:id/groups`
* Remove retrieving Directory Users Groups

Rename endpoints when fetching Directory Groups and Users

---

tests/test_sso.py
workos/sso.py

* Update method documentation to indicate `provider` is a `ConnectionType`
* Convert enum value for Authorization URL

Fix enum to string conversion in `get_authorization_url`

---

setup.py
workos/__about__.py

Install enum34 only on Python < 3.4 where it does not exist.

Install enum34 only on Python < 3.4

---

tests/conftest.py
tests/test_audit_trail.py
tests/utils/test_requests.py
workos/__about__.py
workos/__init__.py
workos/audit_trail.py
workos/resources/base.py
workos/resources/event.py
workos/resources/event_action.py
workos/resources/sso.py
workos/sso.py

- Refactor capture_and_mock_requests
- Add Resource base class
- Add WorkOSEvent and WorkOSEventAction Resources
- Add support for GET /events endpoint

Support for GET /events endpoint

---

workos/__about__.py
workos/audit_trail.py

Don't actually need to wrap the input in `list()`... it would actually break things in this case as it turns out something like `list('abc')` results in `['a', 'b', 'c']`.
For requests, we can actually pass in the input as is because a string and a single element array are represented the same way by python requests. `'foo'` and `['foo']` would be transformed into `/events?group=foo`.

Fix get_events filtering

---

tests/test_audit_trail.py
workos/__about__.py
workos/audit_trail.py

Misinterpreted how the filters were being used App side. Direction is determined by before and after. Beyond that, both params will also be used in filtering so we shouldn't restrict both of them being used.

Remove restriction on before and after params for get events

---

tests/test_sso.py
workos/__about__.py
workos/resources/sso.py

* On the API, we recently exposed raw_attributes, the original profile
response we receive from the IdP. This update passes this data through
the SDK.
* Updates the SDK to 0.5.0

Expose raw_attributes on WorkOSProfile

---

tests/test_portal.py
workos/portal.py

* Adds the ability to create an organization via the SDK for use
with the Admin Portal.

Add create_organization function to Portal module

---

tests/test_portal.py
workos/portal.py

* Adds an SDK method to generate an Admin Portal link.

Add generate_link function to Portal module

---

tests/test_passwordless.py
workos/passwordless.py
workos/utils/validation.py

Add Passwordless support for MagicLink. Adds two methods:
- `create_session` - generate a passwordless session for a user from their email
- `send_session` - send an email to a user with a Magic Link confirmation URL

Add MagicLink support through passwordless module

---

tests/test_sso.py
workos/__about__.py
workos/resources/sso.py

* Passes the `connection_id` Profile object attribute through to the SDK. We currently expose `connection_id` via the `/sso/token` API endpoint.
* Updates the SDK version to `0.8.0`.

Expose `connection_id` on Profile Objects

---

README.md

Updating typo of `Pyhon` in README caught by a customer

Updating to fix typo in Readme Pyhon -> Python

---

tests/test_sso.py
workos/sso.py

- Adds functionality to retrieve a list of Connections using the WorkOS SSO REST API

Add `GET /connections`

---

tests/test_sso.py
workos/sso.py

- Adds functionality to retrieve a single Connection using the WorkOS SSO REST API

Add `GET /connections/:id`

---

workos/sso.py

- Adds support for an `organization_id` parameter to the `list_connections` function. Allows for retrieving a list of all Connections associated with the given `organization_id`.

Add `organization_id` Parameter to `list_connections`

---

tests/test_client.py
tests/test_sso.py
workos/__about__.py
workos/utils/validation.py

Added some logic to support either client_id or project_id in the SSO module
I adjusted tests and added one to check for a deprecation warning when using project_id

Fix bug in supporting client id

---

workos/exceptions.py
workos/utils/request.py

Implement `__str__` for a human-readable format as exceptions come up.

feat(workos-python): Implement `__str__` for `BaseRequestException`

---

workos/passwordless.py

Support connection param for Create Passwordless Session endpoint in Python SDK.

Add optional session_option[connection] param to docstring

---

tests/test_sso.py
workos/resources/sso.py
workos/sso.py

This PR renames the `get_profile` method to `get_profile_and_token`.
This is a breaking change that will be part of `v1.0.0`.
Resolves SDK-157.

Rename `get_profile` to `get_profile_and_token`

---

tests/test_organizations.py
tests/test_portal.py
workos/organizations.py
workos/portal.py
workos/utils/validation.py

This PR moves the Organization operations to their own top-level class in the SDK.
This is a breaking change that will be part of `v1.0.0`.
Resolves SDK-170.

Move Organization operations to the top-level

---

tests/test_sso.py
workos/sso.py

This PR removes the deprecated `create_connection` and `promote_draft_connection` methods from the SDK.
This is a breaking change that will be part of `v1.0.0`.
Resolves SDK-178.

Remove `create_connection` and `promote_draft_connection` methods

---

tests/test_directory_sync.py
tests/test_sso.py
workos/directory_sync.py

Add `delete_directory()` endpoint to Python SDK

Add `delete_directory` endpoint

---

tests/test_client.py
workos/client.py
workos/utils/validation.py

This PR fixes an issue where the `organizations` property was missing from the `Client`.
Resolves SDK-195.

Expose `organizations` on `Client`

---

setup.py

Just noticed that we still have the `Development Status :: 1 - Planning` classifier.
Now that we're 1.0 I think it makes sense to switch to `Development Status :: 5 - Production/Stable`.

Change development status classifier to "Production/Stable"

---

tests/test_organizations.py
workos/organizations.py
workos/utils/request.py

Adds the update organization method

Add update organization method

---

tests/test_organizations.py
workos/organizations.py

Adds delete organization method

Add delete organization method

---

tests/utils/test_requests.py
workos/exceptions.py
workos/utils/request.py

Add support for `error` and `error_description` for 400 errors. Targeting better error handling in SDKs for the POST /sso/token endpoint

Add support for error and error_description

---

tests/test_directory_sync.py

https://linear.app/workos/issue/SDK-218/add-organizationid-to-directory-endpoint-python-sdk
No need to add `organization_id` to the Directory endpoint for Python, but updating relevant Directory Sync tests.

Add OrganizationId to Directory tests

---

tests/test_audit_trail.py
tests/test_directory_sync.py
tests/test_organizations.py
tests/test_passwordless.py
tests/test_portal.py
tests/test_sso.py
workos/audit_trail.py

This PR begins the process of cleaning up the mocks in our tests.
Previously we were double mocking our response objects, which was simulating a response object being returned from the WorkOS API, which is not correct.

Clean up test mocking

---

tests/conftest.py
tests/test_directory_sync.py
tests/test_organizations.py
tests/test_sso.py
workos/utils/request.py

This PR fixes an issue where we were trying to parse the response body as JSON for API responses that did not return JSON.
We now only parse the response body as JSON if it has a `Content-Type` of `application/json`.
Closes #80.

Only attempt to parse JSON for JSON responses

---

tests/conftest.py
tests/utils/test_requests.py
workos/utils/request.py

The [`Content-Type`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) header is frequently sent like `application/json`, [but it can also contain extra "subtypes" like `; charset=utf8`](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html). This leads to an issue with our response handling, as it compares the entire header value (like `application/json; charset=urf8`) against `application/json` to determine if the response was JSON.
These changes make that check less exact, and instead we only look to see if the header contains `application/json`, and then attempt to deserialize JSON.

Handle `Content-Type` headers that contain an encoding

---

workos/organizations.py

This PR documents the `allow_profiles_outside_organization` field for organizations.
Resolves SDK-258.

Document `allow_profiles_outside_organization` for organizations

---

tests/test_sso.py
workos/resources/base.py

This PR fixes an issue where fields not present in a JSON response would result in a `KeyError` being thrown (as described in #102).
Now, if the key is not present in the response we use `None` as the value instead.

Use `None` for fields that do not exist

---

tests/test_sso.py
workos/sso.py

This PR adds support for the `organization` parameter to initiate SSO.
As part of this, the `domain` parameter has also been deprecated in favor of `organization`.
Resolves SDK-356.

Add support for `organization` parameter

---

tests/test_sso.py
workos/sso.py

Currently if customers don't provide a redirectURI in the getAuthorizationURI function they do not get an error from the SDK, but will receive an error in the browser. We can improve the user experience by raising this error in the SDK instead of the browser.

Create a requirement for RedirectURI in GetAuthorizationURL function

---

tests/test_sso.py
workos/sso.py

This PR updates the handling of the `connection_type` parameter for the `sso.list_connections` method to support passing a `ConnectionType` enum value.
To retain backwards compatibility, we attempt to coerce any string values to their corresponding `ConnectionType` values. If given an invalid string, an exception will be thrown. This should not be a breaking change, as we already validate the connection types on the API side. All we're doing is moving the validation up into the SDK.
Fixes #110.
Closes #111.

Make `connection_type` for `list_connections` accept enum values

---

.github/CODEOWNERS

This PR updates the `CODEOWNERS` file after the GitHub organization rename.

Update CODEOWNERS after organization rename

---

tests/test_mfa.py
workos/__about__.py
workos/mfa.py

This PR updates the endpoints used for two of the MFA operations:
- `challenge_factor`
- `verify_challenge`
The `verify_factor` method is now deprecated and has been replaced with `verify_challenge`. `verify_factor` will be removed in the next major version.
Resolves SDK-547.

Update endpoints used for MFA operations

---

tests/conftest.py
tests/test_audit_logs.py
tests/test_client.py
workos/audit_logs.py
workos/client.py
workos/exceptions.py
workos/resources/audit_logs_export.py
workos/utils/request.py

Add AuditLogs calls to the SDK:
-  `create_event`
-  `create_export`
-  `get_export`
Also made a few tweaks to expose `code` and `errors` payload in exceptions.

Add Audit Logs to the Python SDK

---

workos/__about__.py

Bump version to v1.21.0

---

tests/test_sso.py
workos/resources/sso.py

Adds new groups attribute to SSO user profile.
```
[ ] Yes
```

Add groups attribute to SSO user profile

---

workos/directory_sync.py
workos/organizations.py
workos/sso.py

Update default limit check for list methods. This resolves the bug where you receive an error on calling a list method with the default limit set. 
```
[ ] Yes
```

Update default limit check for list methods

---

tests/test_events.py
tests/utils/fixtures/mock_event.py
workos/client.py
workos/events.py
workos/utils/validation.py

Add support to get a list of events from the `Events` service. Introduces a new module for `Events`, and the corresponding endpoint. 
```
[ ] Yes
```

Add method to `get_events` from `Events` service

---

tests/test_audit_logs.py
workos/audit_logs.py

- Adds `actor_names` and `actor_ids` to `create_export`
- Deprecates `actors` in favor of `actor_names`
```
[ ] Yes
```

Add `actor_names` and `actor_ids` to `create_export`

---

tests/test_events.py
workos/events.py

More cohesive with the other `list_X` API methods 
```
[ ] Yes
```

Update `get_events` to `list_events`

---

tests/test_client.py
tests/test_users.py
tests/utils/fixtures/mock_user.py
workos/client.py
workos/resources/users.py
workos/users.py
workos/utils/validation.py

Add `Users` client and `Users.create_user()` method

---

tests/test_users.py
tests/utils/fixtures/mock_user.py
workos/users.py
workos/utils/user_types.py

Add `Users.list_users()`

---

tests/test_users.py
workos/users.py

Add `Users.authenticate_with_password()`

---

tests/test_users.py
workos/users.py

Add `Users.complete_password_reset()` method

---

tests/test_users.py
workos/users.py

Add `Users.verify_email()` method

---

tests/test_users.py
workos/users.py

Add `users.update_user_password()` method

---

tests/test_users.py
workos/users.py

Add `users.update_user()` method

---

tests/test_client.py
tests/test_user_management.py
workos/client.py
workos/user_management.py
workos/utils/validation.py

Renames the `User` class to `UserManagement`
```
[ ] Yes
```

Rename Users to UserManagement

---

tests/test_user_management.py
workos/user_management.py

Updates the `get_user`, `list_users`, and `delete_user` methods to match the current User Management API.
```
[ ] Yes
```

Fix `get_user`, `list_users`, and `delete_user` methods

---

tests/test_user_management.py
workos/user_management.py

Finalizes the `send_magic_auth_code` method
```
[ ] Yes
```

Finalize `send_magic_auth_code` method

---

tests/test_user_management.py
tests/utils/fixtures/mock_invitation.py
workos/resources/user_management.py
workos/user_management.py

Adds methods and resources for the invitations API (part of user management)
```
[ ] Yes
```

Add invitations API methods

---

tests/test_user_management.py
workos/resources/user_management.py
workos/user_management.py

Finalizes all the `authorize_with_*` methods
```
[ ] Yes
```

Finalize `authorize_with_*` methods

---

tests/test_user_management.py
workos/user_management.py

Finalizes the create and update users API methods
```
[ ] Yes
```

Finalize create and update users API

---

tests/test_user_management.py
workos/user_management.py

Finalizes the password reset methods and the `send_magic_auth_code` method.
```
[ ] Yes
```

Finalize password reset and send magic auth methods

---

tests/test_sso.py
tests/test_user_management.py
workos/sso.py
workos/user_management.py
workos/utils/provider_types.py
workos/utils/sso_provider_types.py
workos/utils/um_provider_types.py

Adds the UM specific `get_authorization_url` method.
```
[ ] Yes
```

Add UM `get_authorization_url` method

---

workos/__about__.py

Added:
- Added GitHubOAuth as a provider (#228)
```
[ ] Yes
```

Bump version to 2.1.0

---

.semaphore/semaphore.yml
workos/__about__.py
workos/directory_sync.py
workos/organizations.py
workos/resources/list.py
workos/sso.py
workos/user_management.py

- Default list methods to descending order. 
- Remove tests on python v2 
```
[ ] Yes
```

chore: default list methods to descending order

---

tests/conftest.py
tests/test_directory_sync.py
tests/test_sso.py
tests/test_user_management.py
tests/test_webhooks.py
workos/resources/user_management.py
workos/webhooks.py

Adds support for the impersonator metadata in authentication responses.
```
[ ] Yes
```

Add "impersonator" field to `WorkOSAuthenticationResponse`

---

.semaphore/publish.yml

Saw the following error when attempting to publish a new version:
```
[20:04 21/03/2024]: Changing 'python' to version 3.700:00
Usage:00:00
change-python-version <version>00:00
Supported versions are: 3.12, 3.11, 3.1000:00
! [20:04 21/03/2024]: Failed to switch version.
```
I imagine this was related to the recent Semaphore image changes.
```
[ ] Yes
```

Bump version of python in `publish.yml` workflow

---

.github/workflows/release.yml

This migrates our release process from Semaphore to GitHub Actions
```
[ ] Yes
```

Automatically push to PyPI when a Release is created

---

workos/__about__.py
workos/user_management.py

`role_slug` is an optional parameter when sending an invite
```
[ ] Yes
```

Add `role_slug` to user management send invitation flow

---

workos/__about__.py
workos/user_management.py

This PR ensures that the User create process allows for the `password_hash` and `password_hash_type` fields, in addition to the existing `password` field, similar to the Update process.
```
[x] Yes
```
https://github.com/workos/workos/pull/26060

Add 'password_hash' and 'password_hash_type' to User creation

---

workos/mfa.py

This PR aims at fixing the string interpolation when building MFA URLs.
This is to address https://github.com/workos/workos-python/issues/252

Fix string interpolation when building MFA URLs

---

tests/utils/test_requests.py
workos/mfa.py
workos/utils/request.py

This is to ensure we have the right helpers (and test coverage) to build URLs in the right way, and not experience code defects as the ones reported recently.

Explicit coverage over creation of parameterized URLs

---

tests/test_events.py
tests/utils/fixtures/mock_event.py
workos/events.py

Support passing in `organization_id` as a valid parameter when calling the Events API 
```
[ ] Yes
```

Add `organization_id` support for Events API

---

tests/test_user_management.py
tests/utils/fixtures/mock_invitation.py
tests/utils/fixtures/mock_magic_auth.py
workos/resources/user_management.py
workos/user_management.py

Adds events and API changes to support sending your own emails for invitations and Magic Auth.
- Adds `accept_invitation_url` to invitation object returned by API
- Adds new endpoints for the Magic Auth API: `get_magic_auth` and `create_magic_auth`
- Deprecates current `send_magic_auth_code` method in favor of `create_magic_auth`
```
[x] Yes
```
https://github.com/workos/workos/pull/26691

Add API changes for invitations and Magic Auth

---

tests/test_user_management.py
tests/utils/fixtures/mock_email_verification.py
tests/utils/fixtures/mock_invitation.py
tests/utils/fixtures/mock_password_reset.py
workos/resources/user_management.py
workos/user_management.py

- Add `inviter_user_id` to invitation object
- Add `GET /user_management/email_verification/:id` endpoint
- Add `GET /user_management/password_reset/:id` and `POST /user_management/password_reset` endpoints
- Deprecate current send password reset endpoint
```
[x] Yes
```
https://github.com/workos/workos/pull/27414

Add methods and events for email verification and password reset

---

tests/test_user_management.py
workos/__about__.py
workos/user_management.py

Fix bug with trailing forward slash in JWKS and logout URLs.
Fixes https://github.com/workos/workos-python/issues/269
```
[ ] Yes
```

Fig bug with JWKs and logout URL

---

tests/utils/fixtures/mock_directory_user.py
workos/__about__.py
workos/resources/directory_sync.py

Optional property on the directory sync user object.
```
[ ] Yes
```

Add role to Directory Sync User object

---

workos/organizations.py
workos/user_management.py

Deprecates the `allow_profiles_outside_organization` parameter. Additionally, updates the create/update Organization methods to only serialize these options if an actual value has been passed.
Previously, `null` was always sent, which was fine for this particular endpoint, but is not a pattern that is guaranteed to have the same semantics everywhere.
```
[ ] Yes
```

Deprecate `allow_profiles_outside_organization` parameter

---

tests/test_organizations.py
tests/utils/fixtures/mock_organization.py
workos/organizations.py
workos/resources/organizations.py

NOTE: the lookup_key feature is not generally available right now.
```
[ ] Yes
```

Add `lookup_key` support

---

workos/user_management.py
workos/utils/connection_types.py
workos/utils/sso_provider_types.py
workos/utils/um_provider_types.py

Add `AppleOAuth` constants so SDK users can kick off login flows with Sign in with Apple.
The `ConnectionType.GitHubOAuth` constant was never added to this SDK, adding it too.
```
[ ] Yes
```

Add AppleOAuth and GitHubOAuth constants

---

tests/conftest.py
tests/test_client.py
tests/test_directory_sync.py
tests/test_organizations.py
tests/test_sso.py
tests/utils/fixtures/mock_connection.py
workos/async_client.py
workos/client.py
workos/directory_sync.py
workos/events.py
workos/organizations.py
workos/resources/list.py
workos/resources/sso.py
workos/sso.py
workos/user_management.py
workos/utils/_base_http_client.py
workos/utils/connection_types.py
workos/utils/http_client.py
workos/utils/request.py
workos/utils/sso_provider_types.py

Add typing and async support for SSO.
```
[ ] Yes
```

Add typing and async support for SSO

---

workos/directory_sync.py
workos/events.py
workos/organizations.py
workos/resources/list.py
workos/sso.py

Making this a union was the wrong choice. It requires the developer to handle the scenario where `before` does not exist in the dictionary for all list resources. It's only the case for Events.
This type var lets us return the correct type for each resource.
```
[ ] Yes
```

List resource returns more specific type

---

tests/conftest.py
tests/test_sso.py
tests/test_user_management.py
tests/utils/fixtures/mock_auth_factor_totp.py
tests/utils/fixtures/mock_connection.py
tests/utils/fixtures/mock_email_verification.py
tests/utils/fixtures/mock_invitation.py
tests/utils/fixtures/mock_magic_auth.py
tests/utils/fixtures/mock_organization.py
tests/utils/fixtures/mock_organization_membership.py
tests/utils/fixtures/mock_password_reset.py
tests/utils/fixtures/mock_user.py
workos/client.py
workos/directory_sync.py
workos/events.py
workos/resources/list.py
workos/resources/mfa.py
workos/resources/organizations.py
workos/resources/user_management.py
workos/sso.py
workos/types/events/directory_payload_with_legacy_fields.py
workos/user_management.py
workos/utils/_base_http_client.py
workos/utils/request.py
workos/utils/um_provider_types.py

Add typing for User Management.
```
[ ] Yes
```

Add typing for User Management

---

workos/user_management.py

Adds the new `organization_id` parameter to the User Management `authenticate_with_refresh_token` method.
```
[ ] Yes
```

Add `organization_id` parameter to `authenticate_with_refresh_token`

---

tests/test_organizations.py
tests/test_portal.py
workos/client.py
workos/organizations.py
workos/portal.py
workos/resources/portal.py

Add typing for portal and use new HTTP client for organizations.
```
[ ] Yes
```

Add typing for portal

---

tests/test_passwordless.py
workos/client.py
workos/passwordless.py
workos/resources/passwordless.py

Add typing for Passwordless APIs.
```
[ ] Yes
```

Add typing for Passwordless APIs

---

tests/test_user_management.py
workos/directory_sync.py
workos/resources/directory_sync.py
workos/user_management.py

We no longer support querying directories by domain.
```
[ ] Yes
```

Remove domain param from directories query

---

tests/test_organizations.py
workos/directory_sync.py
workos/events.py
workos/organizations.py

Fix methods missing _id for unique IDs.
```
[ ] Yes
```

Fix methods missing _id for unique IDs

---

.github/workflows/release.yml

Update release.yml to support pre-releases.
```
[ ] Yes
```

Update release.yml to support pre-releases

---

workos/__about__.py

Bump to version 5.0.0beta1.
```
[ ] Yes
```

Bump to version 5.0.0beta1

---

tests/test_webhooks.py
workos/resources/webhooks.py
workos/webhooks.py

Add type hints to `verify_event`. Unfortunately, this lead to a bunch of duplication, comments inline.
```
[ ] Yes
```

Type webhook methods

---

tests/test_webhooks.py
workos/typing/webhooks.py
workos/webhooks.py

This turned out to be simpler than handling untyped literals. Added an `UntypedWebhook` with a very general signature. It's the last type checked. As long as the content follows our rough webhook shape, the `UntypedWebhook` will be returned.
```
[ ] Yes
```

Return untyped webhook

---

tests/test_directory_sync.py
workos/directory_sync.py
workos/sso.py

The SDK was still a mixed bag of `_id` IDs and those without. This converts all IDs to end with `_id`
```
[ ] Yes
```

Consistently use _id of IDs

---

workos/resources/mfa.py
workos/resources/sso.py
workos/types/events/authentication_payload.py

Optional fields must have a default value, otherwise they result in an error and deserialization when there is no value for that attributes. Also, switched over to using `Optional` for consistency. Also fine with switching everything to `Union[FOO, None]`, but I think we should consistently use one style.
```
[ ] Yes
```

Fix sso profile resource

---

tests/conftest.py
tests/test_directory_sync.py
tests/test_organizations.py
tests/test_sso.py
workos/directory_sync.py
workos/events.py
workos/organizations.py
workos/resources/list.py
workos/sso.py
workos/user_management.py

Remove need to call `auto_paging_iter` and use single WorkOsListResource for sync and async.
With this change, list() methods can be used in two ways:
```
organization_memberships = (
workos.client.user_management.list_organization_memberships(
organization_id="org_01HB6C9FZWRPDTVQ3YNBB1Q3JB"
)
)
```
OR
```
all_organization_memberships = []
for (
organization_membership
) in workos.client.user_management.list_organization_memberships(
organization_id="org_01HB6C9FZWRPDTVQ3YNBB1Q3JB",
):
all_organization_memberships.append(organization_membership)
```
```
[ ] Yes
```
If yes, link a related docs PR and add a docs maintainer as a reviewer. Their approval is …

Remove need to call `auto_paging_iter` and use single WorkOsListResource for sync and async

---

tests/types/test_directory_state.py
workos/types/directory_sync/directory_state.py

We made this conversion for `active` but forgot to do so for `inactive`
Resolves DSYNC-1785
```
[ ] Yes
```

Change unlinked directory state to inactive and convert in validator

---

workos/types/events/authentication_payload.py

The Authentication type had two bugs:
- It was always requiring `created_at` in the payload, which does not actually exist
- There was a typo in the oauth type
```
[ ] Yes
```

Fix type for authentication events

---

tests/test_audit_logs.py
tests/test_directory_sync.py
tests/test_mfa.py
tests/test_organizations.py
tests/test_passwordless.py
tests/test_portal.py
tests/test_user_management.py
tests/test_webhooks.py
workos/async_client.py
workos/audit_logs.py
workos/client.py
workos/directory_sync.py
workos/events.py
workos/mfa.py
workos/organizations.py
workos/passwordless.py
workos/portal.py
workos/sso.py
workos/user_management.py
workos/webhooks.py

Switch multi-arg public SDK methods to keyword-only.
```
[ ] Yes
```

Require kwargs for multi param methods

---

tests/test_fga.py
workos/fga.py
workos/types/__init__.py
workos/types/fga/check.py
workos/types/fga/resource_types.py
workos/types/fga/resources.py
workos/types/fga/warrant.py
workos/utils/_base_http_client.py
workos/utils/pagination_order.py

Update FGA to match our conventions:
- Use duck types when possible
- Use `TypedDict` for complex input types
- Use string literals rather than enums
- Re-export input types from the `types` module for convenience
Stacked on #335
```
[ ] Yes
```

Fga type updates

---

tests/test_organizations.py
tests/test_user_management.py
workos/async_client.py
workos/organizations.py
workos/types/list_resource.py
workos/types/webhooks/webhook.py
workos/user_management.py
workos/utils/_base_http_client.py
workos/webhooks.py

Add async support for organizations. This is the last module I felt like async support could absolutely be useful, in tandem with other modules.
```
[ ] Yes
```

Add async support for organizations

---

workos/fga.py
workos/types/fga/__init__.py
workos/types/fga/authorization_resource_types.py
workos/types/fga/authorization_resources.py
workos/types/fga/list_filters.py
workos/types/list_resource.py

Rename `Resource` because we also use that term for endpoints, like `ListResource`.
Upon further though, I'm now on the fence with this one. The `Resource` is nested in the FGA types. And I'm not loving any of the renames.
`AuthorizationResource` - Is that what this is? Is it actually an `AuthorizableResource`? So far I've gone with `AuthorizationResource`.
`FGAResource` - Meh, I don't love acronyms.
`WarrantResource` - Feels like this is shipping our org structure and just prefixing with `Warrant`.
Stacked on #336  if we want to merge this. I'd love the reviewers thoughts.
```
[ ] Yes
```
If yes, link a related docs PR and add a docs maintainer as a …

Rename FGA types

---

workos/types/user_management/list_filters.py
workos/user_management.py

Fix list_organization_memberships statuses parameter when auto paging.
```
[ ] Yes
```

Fix list_organization_memberships statuses parameter when auto paging

---

tests/conftest.py
tests/test_sso.py
tests/test_user_management.py
tests/utils/client_configuration.py
workos/sso.py
workos/utils/_base_http_client.py
workos/utils/request_helper.py

Fix base_url parsing for build_url_with_query_params. Tested against `get_authorization_url` for standalone and UM, but additionally `/organizations`, `/organization_memberships`, and `/events`.
Fixes #341.
```
[ ] Yes
```

Fix base_url parsing for build_url_with_query_params

---

workos/__about__.py

Bump version to 5.0.1 to fix base_url behavior.
```
[ ] Yes
```

Bump version to 5.0.1

---

workos/types/audit_logs/audit_log_export.py
workos/types/fga/check.py
workos/types/mfa/authentication_factor.py
workos/types/user_management/organization_membership.py

Make OrganizationMembership.status LiteralOrUntyped.
```
[ ] Yes
```

Add missing LiteralOrUntyped wrappers

---

tests/test_fga.py
workos/types/fga/check.py
workos/types/fga/warrant.py

Fixes issue where `TypeError: Object of type Subject is not JSON serializable` would make `batch_write_warrants` and `check` methods unusable.

[BUG] Fix issue with Subject not serializing properly in FGA module

---

tests/test_portal.py
workos/types/portal/portal_link_intent.py

Adding the certificate renewal intent as an option for link generation
```
[ ] Yes
```

Add certificate renewal intent

---

tests/conftest.py
tests/test_directory_sync.py
tests/test_organizations.py
tests/test_sso.py

Use syncify for remaining async test suites.
```
[ ] Yes
```

Use syncify for remaining async test suites

---

workos/sso.py
workos/user_management.py

Add documentation about sync-only methods.
```
[ ] Yes
```

Add documentation about sync-only methods

---

tests/test_async_http_client.py
tests/test_sync_http_client.py
workos/exceptions.py
workos/utils/_base_http_client.py

Exceptions were only returning specific hardcoded values, which isn't accurate any more since an error can have a plethora of parameters in it. 
This fixes it by dumping the contents of the API response into the error object, giving the user all the information they need to fix the error.
```
[ ] Yes
```

Fix authentication error payload

---

workos/types/events/event.py
workos/types/events/event_type.py

Add missing organization membership types to Event type union. Fixes #362.
```
[ ] Yes
```

Add missing organization membership types to Event type union

---

workos/__about__.py

Bump version to 5.4.2.
```
[ ] Yes
```

Bump version to 5.4.2

---

workos/types/webhooks/webhook.py

Add missing organization membership webhook events to union. Fixes #365.
```
[ ] Yes
```

Add missing organization membership webhook events to union

---

tests/test_webhooks.py
tests/utils/fixtures/mock_event.py
workos/types/events/directory_payload_with_legacy_fields.py
workos/types/events/event.py
workos/types/events/event_model.py

Fix incorrect `dsync.activated` domains type for Events API, causing a parsing error when listing `dsync.activated` events with domains.
This PR leaves the webhooks event payload as a dictionary. This will be changed in the next major version.
```
[ ] Yes
```

Fix dsync.activated event parsing for Event API when domains present

---

workos/__about__.py

Bump to version 5.4.4 for bug fix.
```
[ ] Yes
```

Bump to version 5.4.4

---

tests/test_sso.py
tests/utils/fixtures/mock_profile.py
workos/types/sso/profile.py

Adds "role" property to profile.
```
[X] Yes
```
[Docs PR](https://github.com/workos/workos/pull/31033/)

Add "role" to profile

---

workos/__about__.py

Bump to version 5.5.1 for dependency updates.
```
[ ] Yes
```

Bump to version 5.5.1 for dependency updates

---

workos/types/user_management/authentication_response.py
workos/types/user_management/oauth_tokens.py

Created a new `OAuthTokens` model to represent OAuth credentials, including provider, access token, refresh token, expiration, and scopes. Integrated this new model into the `AuthenticationResponse` class, adding an optional field for OAuth tokens.
```
[ ] Yes
```

Add `oauth_tokens` to AuthkitAuthenticationResponse

---

tests/test_client.py
tests/test_widgets.py
workos/async_client.py
workos/client.py
workos/types/widgets/__init__.py
workos/types/widgets/widget_scope.py
workos/types/widgets/widget_token_response.py
workos/widgets.py

Add widgets module and widget get token API endpoint.
```
[ ] Yes
```

Add widgets module and widget get token API endpoint

---

workos/types/user_management/authentication_response.py

Adds `"Passkey"` as a possible value of `AuthenticationMethod`.
```
[ ] Yes
```

Add `"Passkey"` to `AuthenticationMethod`

---

tests/test_user_management.py
workos/user_management.py

This changset adds the prompt option to generating oauth authorization urls.
```
[ ] Yes
```

Add prompt option to creating authorization urls

---

tests/test_sso.py
tests/utils/fixtures/mock_connection.py
workos/sso.py
workos/types/sso/connection.py

This PR adds `sso.update_connection()` method which allows to update SAML signing keys.
Contact WorkOS support if you want to enable this feature.
```
[ ] Yes
```

Add options to Connection resource and add `sso.update_connection()` method

---

tests/test_async_http_client.py
tests/test_sync_http_client.py
workos/exceptions.py
workos/utils/_base_http_client.py

Propagate ConflictExceptions properly and don't mask them as BadRequestExceptions.
```
[ ] Yes
```

Propagate ConflictExceptions properly

---

tests/test_organizations.py
tests/utils/fixtures/mock_role.py
workos/organizations.py
workos/types/events/event.py
workos/types/events/event_model.py
workos/types/roles/role.py
workos/types/webhooks/webhook.py

Add GET /organization/:orgId/roles support.
```
[ ] Yes
```

Add GET /organization/:orgId/roles support

---

workos/__about__.py

Bump to version 5.11.0.
```
[ ] Yes
```

Bump to version 5.11.0

---

requirements-dev.txt
requirements.txt
tests/test_audit_logs.py
tests/test_mfa.py
tests/test_organizations.py
tests/test_session.py
tests/test_sso.py
tests/test_webhooks.py
workos/user_management.py

Update dependencies and pinning.
```
[ ] Yes
```

Update dependencies and version pinning

---

workos/__about__.py

Bump to version 5.11.1.
```
[ ] Yes
```

Bump to version 5.11.1

---

tests/test_user_management.py
workos/types/user_management/screen_hint.py
workos/user_management.py

Support the `screen_hint` parameter in `user_management.get_authorization_url`
```
[ ] Yes
```

feat: Support screen_hint in user_management.get_authorization_url

---

workos/utils/http_client.py

Don't overwrite default transport, so proxies can be set via environment variables. Tested and confirmed requests work as usual with no proxy, and are proxies properly when setting HTTPS_PROXY and ALL_PROXY environment variables.
```
[ ] Yes
```

Don't overwrite default transport so proxies can be set via environment variables

---

workos/__about__.py

Bump to version 5.12.1.
```
[ ] Yes
```

Bump to version 5.12.1

---

workos/organizations.py
workos/types/organizations/organization.py

Python SDK `update_organization` was missing the parameter `stripe_customer_id` 
```
[ x] Yes
```

adding strip_customer_id to python sdk to support entitlements

---

requirements.txt
setup.py

Adjust version pinning to allow for more cryptography versions. Opened up to 42.0.8, which had a CVE fix.
```
[ ] Yes
```

Adjust version pinning to allow for more cryptography versions

---

workos/__about__.py

Bump to version 5.13.1 for dependency version pinning changes.
```
[ ] Yes
```

Bump to version 5.13.1

---

tests/test_portal.py
workos/portal.py
workos/types/portal/portal_link_intent_options.py

This PR introduces the `intent_options` parameter in the `Portal.generate_link()` method. This feature is not generally available on WorkOS API. Contact WorkOS support for access.
```
[ ] Yes
```

Add `intent_options` parameter on `Portal.generate_link()` method

---

tests/test_user_management.py
tests/utils/fixtures/mock_user.py
workos/types/user_management/user.py

https://linear.app/workos/issue/AUTH-4178/update-workos-python-sdk-for-last-sign-in-at
adds `last_sign_in_at` to user
```
[X] Yes
```
docs PR: https://github.com/workos/workos/pull/35170

add last_sign_in_at to user

---

workos/__init__.py

Add missing list of workos module public symbols.
```
[ ] Yes
```

Add missing list of workos module public symbols

---

workos/__about__.py

Bump to version 5.15.1 to add missing list of workos module public symbols.
```
[ ] Yes
```

Bump to version 5.15.1

---

tests/test_organizations.py
tests/test_user_management.py
tests/utils/fixtures/mock_organization.py
tests/utils/fixtures/mock_user.py
workos/organizations.py
workos/types/metadata.py
workos/types/organizations/organization.py
workos/types/user_management/user.py
workos/user_management.py

Adds external_id and metadata properties to both users and organizations.
Also adds a get_[resource]_by_external_id for users and organizations and deletes the now defunct get_organization_by_lookup_key method.
```
[x] Yes
```

Add metadata and external id to users and organizations

---

tests/test_directory_sync.py
tests/utils/fixtures/mock_directory_user.py
workos/types/directory_sync/directory_user.py

Add email standard attribute to DirectoryUser and mark deprecated standard attributes
```
[ ] Yes
```

Add email standard attribute to DirectoryUser and mark deprecated standard attributes

---

requirements.txt

For libraries, the best practice is to only list **known incompatibilities** and not _potential_ future incompatibilities. Using `<=` (or `~=`) constraints can:
- Lead to dependency resolution conflicts for downstream consumers
- Prevent users from using newer versions of dependencies that are likely still compatible
- Reduce composability in larger environments or monorepos
Note how `pydantic` itself has no [`<=` constraints](https://github.com/pydantic/pydantic/blob/main/pyproject.toml#L45). You'll find the same with other libraries.

Don't arbitrarily constrain dependency versions

---

workos/user_management.py

Add async support for load_sealed_session.
```
[ ] Yes
```

Add async support for load_sealed_session

---

workos/__about__.py

Bump to v5.18.0.
```
[ ] Yes
```

Bump to v5.18.0

---

workos/__about__.py

Bump to 5.18.1 for an async session handling patch.
```
[ ] Yes
```

Bump to 5.18.1

---

workos/types/events/event.py
workos/types/events/event_type.py
workos/types/webhooks/webhook.py

https://linear.app/workos/issue/AUTH-4441/add-password-resetsucceeded-event-to-python-sdk
adds support for password_reset.succeeded event type
```
[ ] Yes
```

add password_reset.succeeded event type

---

workos/types/sso/connection.py

Allow `organization_id` to be optional on `Connection` for OAuth connections.
```
[ ] Yes
```

Allow organization_id to be optional on Connection for OAuth connections

---

tests/conftest.py
tests/test_session.py

Fix async session tests, which were previously being skipped due to an incompatible decorator and missing async markers.
```
[ ] Yes
```

Fix async session tests

---

workos/__about__.py

Bump to version 5.19.1 for patch fixes.
```
[ ] Yes
```

Bump to version 5.19.1

---

requirements.txt

This was causing a dependency conflict when trying to install workos in our api. For the time being we've had to downgrade cryptography back to ~=42.0.8 to satisfy the conflict.
Looking through the changelog and codebase I can't find anything that should require refactoring. 
https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst
```
[ ] Yes
```

Bump cryptography to ~=44.0.2

---

tests/test_sso.py
tests/utils/fixtures/mock_profile.py
workos/types/sso/profile.py

Add `custom_attributes` field to SSO Profile.
```
[ ] Yes
```

Add custom_attributes field to SSO Profile

---

workos/__about__.py

Bump to v5.20.0.
```
[ ] Yes
```

Bump to v5.20.0

---

tests/conftest.py
tests/test_fga.py
workos/fga.py

This PR updates the FGA `query` method to convert the `context` param from a dictionary to a string before making the request.
```
[ ] Yes
```

Convert context into query string for FGA queries

---

tests/test_session.py
workos/session.py

Currently the Session::authenticate() function (which runs on every request and consumes CPU cycles) is decoding the jwt twice unnecessarily. This small refactor fixes that
No

Avoid decoding jwt twice

---

tests/test_fga.py
workos/fga.py
workos/types/fga/__init__.py
workos/types/fga/check.py
workos/types/fga/warnings.py

Adds warning field to check and query response
```json
"warnings": [
{
"code": "missing_context_keys",
"message": "missing context keys required to evaluate policies - results may be incomplete",
"keys": [
"clientIp",
"element1",
"element2"
]
}
]
```

Add warnings field to FGA check / query response

---

workos/user_management.py

Add `email` as option to `UserManagement.update_user`

---

workos/__about__.py

version bump that includes:
- https://github.com/workos/workos-python/pull/469
```
[ ] Yes
```

bump to v5.27.0

---

workos/types/sso/connection.py
workos/types/sso/sso_provider_type.py
workos/types/user_management/authentication_response.py
workos/types/user_management/oauth_tokens.py
workos/types/user_management/user_management_provider_type.py
workos/user_management.py

We are rolling out support for Salesforce OAuth. This adds it to the list of providers.
```
[ ] Yes
```

Add Salesforce OAuth as an authentication provider

---

tests/test_organizations.py
tests/utils/fixtures/mock_feature_flag.py
workos/organizations.py
workos/types/feature_flags/__init__.py
workos/types/feature_flags/feature_flag.py
workos/types/feature_flags/list_filters.py
workos/types/list_resource.py

Adds `list_feature_flags` method to support `GET /organizations/:id/feature-flags`. 
```
[x] Yes
```
Docs to be updated in **AUTH-5314**

Add support for list organization feature flags endpoint
